export type Person = {
    id: number;
    firstName: string;
    lastName: string;
    company: string;
    city: string;
    country: string;
    weekday: string;
    dateReference: string;
    job: string;
    weight: number;
    truckType: string;
    idOperador: number;
    nameAnt: string;
    totalCost: number;
  };
  
  export const data = [
    {
      id: 1,
      firstName: 'Elenora',
      lastName: 'Wilkinson',
      company: 'Bekins',
      city: 'Hertaland',
      country: 'Qatar',
      weekday: 'Monday',
      dateReference: '2025-04-01',
      job: 'Load',
      weight: 1230.5,
      truckType: 'Flatbed',
      idOperador: 101,
      nameAnt: 'Carlos López',
      totalCost: 13400,
    },
    {
      id: 2,
      firstName: 'Berneice',
      lastName: 'Feil',
      company: 'Bekins',
      city: 'Millcreek',
      country: 'Nepal',
      weekday: 'Tuesday',
      dateReference: '2025-04-02',
      job: 'Load',
      weight: 980.3,
      truckType: 'Box Truck',
      idOperador: 102,
      nameAnt: 'Marta Reyes',
      totalCost: 11800,
    },
    {
      id: 3,
      firstName: 'Frieda',
      lastName: 'Baumbach',
      company: 'Bekins',
      city: 'Volkmanside',
      country: 'Croatia',
      weekday: 'Wednesday',
      dateReference: '2025-04-03',
      job: 'Load',
      weight: 1500.0,
      truckType: 'Tanker',
      idOperador: 103,
      nameAnt: 'Luis Ortega',
      totalCost: 14600,
    },
    {
      id: 4,
      firstName: 'Zachery',
      lastName: 'Brown',
      company: 'Bekins',
      city: 'Faychester',
      country: 'Saint Pierre and Miquelon',
      weekday: 'Thursday',
      dateReference: '2025-04-04',
      job: 'Load',
      weight: 1100.8,
      truckType: 'Reefer',
      idOperador: 104,
      nameAnt: 'Sandra Villa',
      totalCost: 12700,
    },
    {
      id: 5,
      firstName: 'Kendra',
      lastName: 'Bins',
      company: 'Bekins',
      city: 'New Valentin',
      country: 'Senegal',
      weekday: 'Friday',
      dateReference: '2025-04-05',
      job: 'Load',
      weight: 890.4,
      truckType: 'Dump Truck',
      idOperador: 105,
      nameAnt: 'Pedro Díaz',
      totalCost: 11500,
    },
    {
      id: 6,
      firstName: 'Lysanne',
      lastName: 'Fisher',
      company: 'Bekins',
      city: 'Malachitown',
      country: 'Costa Rica',
      weekday: 'Saturday',
      dateReference: '2025-04-06',
      job: 'Load',
      weight: 1320.9,
      truckType: 'Flatbed',
      idOperador: 106,
      nameAnt: 'Julia Fernández',
      totalCost: 13900,
    },
    {
      id: 7,
      firstName: 'Garrick',
      lastName: 'Ryan',
      company: 'Bekins',
      city: 'East Pearl',
      country: 'Cocos (Keeling) Islands',
      weekday: 'Sunday',
      dateReference: '2025-04-07',
      job: 'Load',
      weight: 1450.0,
      truckType: 'Box Truck',
      idOperador: 107,
      nameAnt: 'Nicolás Guzmán',
      totalCost: 14150,
    },
    {
      id: 8,
      firstName: 'Hollis',
      lastName: 'Medhurst',
      company: 'Coleman',
      city: 'West Sienna',
      country: 'Papua New Guinea',
      weekday: 'Monday',
      dateReference: '2025-04-08',
      job: 'P Y C',
      weight: 1050.7,
      truckType: 'Tanker',
      idOperador: 108,
      nameAnt: 'Lucía Cabrera',
      totalCost: 12560,
    },
    {
      id: 9,
      firstName: 'Arlo',
      lastName: 'Buckridge',
      company: 'Coleman',
      city: 'Chino',
      country: 'Congo',
      weekday: 'Tuesday',
      dateReference: '2025-04-09',
      job: 'P Y C',
      weight: 900.2,
      truckType: 'Reefer',
      idOperador: 109,
      nameAnt: 'Ricardo Torres',
      totalCost: 11020,
    },
    {
      id: 10,
      firstName: 'Rickie',
      lastName: 'Auer',
      company: 'Coleman',
      city: 'Nyahfield',
      country: 'Sudan',
      weekday: 'Wednesday',
      dateReference: '2025-04-10',
      job: 'P Y C',
      weight: 1350.6,
      truckType: 'Dump Truck',
      idOperador: 110,
      nameAnt: 'Esteban Méndez',
      totalCost: 13890,
    },
    {
      id: 11,
      firstName: 'Isidro',
      lastName: 'Larson',
      company: 'Coleman',
      city: 'Fort Rosinaside',
      country: 'Belize',
      weekday: 'Thursday',
      dateReference: '2025-04-11',
      job: 'P Y C',
      weight: 1225.4,
      truckType: 'Flatbed',
      idOperador: 111,
      nameAnt: 'Marina Campos',
      totalCost: 13300,
    },
    {
      id: 12,
      firstName: 'Bettie',
      lastName: 'Skiles',
      company: 'Coleman',
      city: 'West Feltonchester',
      country: 'Poland',
      weekday: 'Friday',
      dateReference: '2025-04-12',
      job: 'P Y C',
      weight: 1150.0,
      truckType: 'Box Truck',
      idOperador: 112,
      nameAnt: 'Germán López',
      totalCost: 12980,
    },
  ] as Person[];
  